'use client';

export const carsBrandsList = {
  1: 'تويوتا Toyota',
  2: 'فورد Ford',
  3: 'شيفروليه Chevrolet',
  4: 'هوندا Honda',
  5: 'نيسان Nissan',
  6: 'هيونداي Hyundai',
  7: 'كيا Kia',
  8: 'فولكسفاغن Volkswagen',
  9: 'مرسيدس-بنز Mercedes-Benz',
  10: 'بي إم دبليو BMW',
  11: 'أودي Audi',
  12: 'رينو Renault',
  13: 'بيجو Peugeot',
  14: 'سوزوكي Suzuki',
  15: 'مازدا Mazda',
  16: 'ميتسوبيشي Mitsubishi',
  17: 'لكزس Lexus',
  18: 'جيب Jeep',
  19: 'دودج Dodge',
  20: 'فيات Fiat',
  21: 'فولفو Volvo',
  22: 'سوبارو Subaru',
  23: 'جاغوار Jaguar',
  24: 'لاند روفر Land Rover',
  25: 'تيسلا Tesla',
  26: 'بورش Porsche',
  27: 'ميني Mini',
  28: 'سانغ يونغ SsangYong',
  29: 'دايهاتسو Daihatsu',
  30: 'إيسوزو Isuzu',
  31: 'أوبل Opel',
  32: 'سيات SEAT',
  33: 'سكودا Skoda',
  34: 'ألفا روميو Alfa Romeo',
  35: 'فيراري Ferrari',
  36: 'لامبورغيني Lamborghini',
  37: 'بنتلي Bentley',
  38: 'رولز رويس Rolls-Royce',
  39: 'أستون مارتن Aston Martin',
  40: 'ماكلارين McLaren',
  41: 'لوتس Lotus',
  42: 'مازيراتي Maserati',
  43: 'كاديلاك Cadillac',
  44: 'لينكولن Lincoln',
  45: 'كرايسلر Chrysler',
  46: 'رام RAM',
  47: 'جي إم سي GMC',
  48: 'بونتياك Pontiac',
  49: 'هولدين Holden',
  50: 'بروتون Proton',
  51: 'بيرلاي Perodua',
  52: 'تاتا Tata',
  53: 'ماهيندرا Mahindra',
  54: 'ماروتي سوزوكي Maruti Suzuki',
  55: 'فاو FAW',
  56: 'جاك JAC',
  57: 'جريت وول Great Wall',
  58: 'بريليانس Brilliance',
  59: 'تشانجان Changan',
  60: 'جيلي Geely',
  61: 'بورغوارد Borgward',
  62: 'دونغفنغ Dongfeng',
  63: 'زوتي Zotye',
  64: 'ليفان Lifan',
  65: 'هافال Haval',
  66: 'فوتون Foton',
  67: 'سينوفا Sinova',
  68: 'روز رايز Roewe',
  69: 'إم جي MG',
  70: 'لادا Lada',
  71: 'غاز GAZ',
  72: 'فاز VAZ',
  73: 'سايبا Saipa',
  74: 'إيران خودرو Iran Khodro',
  75: 'أبولو Apollo',
  76: 'أرتيجا Artega',
  77: 'أرييل Ariel',
  78: 'أستون مارتن Aston Martin',
  79: 'ألفا روميو Alfa Romeo',
  80: 'أوبل Opel',
  81: 'أودي Audi',
  82: 'أوروس Aurus',
  83: 'أوسكار Osca',
  84: 'أوليسيس Ulysse',
  85: 'إدون Edon',
  86: 'إسكاليد Escalade',
  87: 'إف سي في FCV',
  88: 'إكستريم Extreme',
  89: 'إلكتروميكانيكا Electromeccanica',
  90: 'إم جي MG',
  91: 'إم في أي MVI',
  92: 'إميريتي Emirati',
  93: 'إنفينيتي Infiniti',
  94: 'إي دي إس EDS',
  95: 'إي تي في ETV',
  96: 'إيجل Eagle',
  97: 'إيكو Eco',
  98: 'إيماك Emak',
  99: 'إيفوك Evoke',
  100: 'إيكاروس Ikarus',
  101: 'إيلو Elio',
  102: 'إيماك Emak',
  103: 'أباريث Abarth',
  104: 'أراش Arash',
  105: 'أرتينجا Artega',
  106: 'أرينو Arrinera',
  107: 'أستون مارتن Aston Martin',
  108: 'ألفا روميو Alfa Romeo',
  109: 'أميركان لايفان American LaFrance',
  110: 'أميريكان موتورز American Motors',
  111: 'أوبل Opel',
  112: 'أوتوموبيلي تورينو Automobili Torino',
  113: 'أوتوموبيلي لامبورغيني Automobili Lamborghini',
  114: 'أوتوموبيلي ماتيراتسي Automobili Matarazzi',
  115: 'أوتوموبيلي نوتشيولا Automobili Nucciola',
  116: 'غير ذلك',
};
const models = {
  'تويوتا Toyota': [
    'كورولا Corolla',
    'كامري Camry',
    'لاند كروزر Land Cruiser',
    'هايلكس Hilux',
    'راف فور RAV4',
    'بريوس Prius',
    'فورتشنر Fortuner',
    'سيينا Sienna',
    'ياريس Yaris',
    'أفالون Avalon',
  ],
  'فورد Ford': [
    'فيستا Fiesta',
    'فوكس Focus',
    'موستانج Mustang',
    'إكسبلورر Explorer',
    'إسكيب Escape',
    'إف-150 F-150',
    'رينجر Ranger',
    'إيدج Edge',
    'تاوروس Taurus',
    'كوجا Kuga',
  ],
  'شيفروليه Chevrolet': [
    'ماليب Malibu',
    'إمبالا Impala',
    'سبارك Spark',
    'أفيو Aveo',
    'سيلفرادو Silverado',
    'تاهو Tahoe',
    'سويفت Swift',
    'كابتيفا Captiva',
    'كورونادو Coronado',
    'إكوينوكس Equinox',
  ],
  'هوندا Honda': [
    'سيفيك Civic',
    'أكورد Accord',
    'سي آر-في CR-V',
    'أوديسي Odyssey',
    'فيت Fit',
    'ريبلد Rebel',
    'باجمان Bagman',
    'إليسيون Elysion',
    'إنسايت Insight',
    'إتش آر-في HR-V',
  ],
  'نيسان Nissan': [
    'سنترا Sentra',
    'ألتيما Altima',
    'باترول Patrol',
    'صني Sunny',
    'ماكسيما Maxima',
    'إكس-تريل X-Trail',
    'كيكس Kicks',
    'باترول جراند Patrol Grand',
    'جي تي-آر GT-R',
    'روغ Rogue',
  ],
  'هيونداي Hyundai': [
    'إلنترا Elantra',
    'سوناتا Sonata',
    'توسان Tucson',
    'كريتا Creta',
    'أكسنت Accent',
    'كونا Kona',
    'باليساد Palisade',
    'آزيرا Azera',
    'فينتو Verna',
    'آي30 i30',
  ],
  'كيا Kia': [
    'سيراتو Cerato',
    'سبورتاج Sportage',
    'سورينتو Sorento',
    'ريو Rio',
    'كادي Kadjar',
    'ستينغر Stinger',
    'كارينز Carens',
    'بيكانتو Picanto',
    'كواتز Quoris',
    'موهافي Mohave',
  ],
  'فولكسفاغن Volkswagen': [
    'جولف Golf',
    'باسات Passat',
    'تيجوان Tiguan',
    'بولو Polo',
    'أرتيون Arteon',
    'طوارق Touareg',
    'جيتا Jetta',
    'أوبتيما Up',
    'كارافيل Caravelle',
    'سكودا Skoda',
  ],
  'مرسيدس-بنز Mercedes-Benz': [
    'سي كلاس C-Class',
    'إي كلاس E-Class',
    'أس كلاس S-Class',
    'جي كلاس G-Class',
    'جي أل سي GLC',
    'جي أل أس GLS',
    'أي كلاس A-Class',
    'بي كلاس B-Class',
    'أم أي AMG',
    'مايباخ Maybach',
  ],
  'بي إم دبليو BMW': [
    'ثلاثة Series 3',
    'خمسة Series 5',
    'سبعة Series 7',
    'إكس1 X1',
    'إكس3 X3',
    'إكس5 X5',
    'إكس6 X6',
    'إم M-Series',
    'زي4 Z4',
    'آي3 i3',
  ],
  'أودي Audi': [
    'أربعة A4',
    'ستة A6',
    'ثمانية A8',
    'كيو3 Q3',
    'كيو5 Q5',
    'كيو7 Q7',
    'آر8 R8',
    'تي تي TT',
    'أس3 S3',
    'آي ترون e-Tron',
  ],
  'رينو Renault': [
    'كليو Clio',
    'ميغان Megane',
    'كابتشر Captur',
    'داستر Duster',
    'كانجو Kangoo',
    'سينيك Scenic',
    'زوي Zoe',
    'لوغان Logan',
    'سимвول Symbol',
    'الطريق الجديد All-New Road',
  ],
  'بيجو Peugeot': [
    '208',
    '308',
    '508',
    '2008',
    '3008',
    '5008',
    'بارتنر Partner',
    'ريفتر Rifter',
    'تروكستر Traveller',
    'ريكسيل Rifter',
  ],
  'سوزوكي Suzuki': [
    'سويفت Swift',
    'فيتارا Vitara',
    'جيمني Jimny',
    'إسكودو Escudo',
    'سياز Ciaz',
    'إي يو في Ertiga',
    'ريزار Ritz',
    'بالينو Baleno',
    'أرتيجا Artega',
    'سوليو Solio',
  ],
  'مازدا Mazda': [
    'ثري 3',
    'ستة 6',
    'سي إكس-5 CX-5',
    'سي إكس-9 CX-9',
    'إم إكس-5 MX-5',
    'بي تي-5 BT-50',
    'دي إكس DX',
    'سي إكس-3 CX-3',
    'سي إكس-30 CX-30',
    ' Tribute',
  ],
  'ميتسوبيشي Mitsubishi': [
    'لانسر Lancer',
    'أوتلاندر Outlander',
    'باجيرو Pajero',
    'إيكلبس Eclipse',
    'إي كروس Eclipse Cross',
    'ميراج Mirage',
    'أرك Starwagon',
    'ديليكا Delica',
    'أرتيجا Attrage',
    'ستريك Triton',
  ],
  'لكزس Lexus': [
    'آر إكس RX',
    'جي إس GS',
    'إل أس LS',
    'إل إس ES',
    'إن إكس NX',
    'يو إكس UX',
    'آر سي RC',
    'إل سي LC',
    'آي إس IS',
    'جي إكس GX',
  ],
  'جيب Jeep': [
    '랭글ر Wrangler',
    'جراند شيروكي Grand Cherokee',
    'تشيروكى Cherokee',
    'كومباس Compass',
    'رينيجيد Renegade',
    'جلادياتور Gladiator',
    'كوماندر Commander',
    'ليبرتي Liberty',
    'باتريوت Patriot',
    'واجونير Wagoneer',
  ],
  'دودج Dodge': [
    'تشالنجر Challenger',
    'تشارجر Charger',
    'دورانجو Durango',
    'رام RAM',
    'فايبر Viper',
    'نيترو Nitro',
    'كارافان Caravan',
    'داكوتا Dakota',
    'إم إي ME',
    'دايتونا Daytona',
  ],
  'فيات Fiat': [
    'باندا Panda',
    '500',
    'دوبلو Doblo',
    'بيلتو Punto',
    'تيبو Tipo',
    'لينيا Linea',
    'بريڤا Bravo',
    'كروما Cronos',
    'موبي Mobi',
    'أرجو Argó',
  ],
  'فولفو Volvo': [
    'إكس سي 60 XC60',
    'إكس سي 90 XC90',
    'إس 60 S60',
    'إس 90 S90',
    'في 40 V40',
    'في 60 V60',
    'في 90 V90',
    'سي 40 C40',
    'سي 70 C70',
    'بي بي Polestar',
  ],
  'سوبارو Subaru': [
    'فورستر Forester',
    'أوتباك Outback',
    'إمبريزا Impreza',
    'ليجاسي Legacy',
    'إكس في XV',
    'أس آر Ascent',
    'برزة BRZ',
    'كريستا Crosstrek',
    'تريبكا Tribeca',
    'ليفيور Levorg',
  ],
  'جاغوار Jaguar': [
    'إف بايس F-Pace',
    'إي بايس E-Pace',
    'إكس إي XE',
    'إكس أف XF',
    'إكس جي XJ',
    'إف تايب F-Type',
    'آي بايس I-Pace',
    'أس Type-S',
    'دي Type-D',
    'أر Type-R',
  ],
  'لاند روفر Land Rover': [
    'رينج روفر Range Rover',
    'رينج روفر سبورت Range Rover Sport',
    'رينج روفر فيلار Velar',
    'رينج روفر إيفوك Evoque',
    'ديفندر Defender',
    'ديسكفري Discovery',
    'ديسكفري سبورت Discovery Sport',
    'فري لاندر Freelander',
    'سي دي CD',
    'إس دي SD',
  ],
  'تيسلا Tesla': [
    'موديل 3 Model 3',
    'موديل إس Model S',
    'موديل إكس Model X',
    'موديل واي Model Y',
    'سايبر ترك Cybertruck',
    'رودستر Roadster',
    'سيمنت Semi',
    'إس بي SP',
    'إي تي ET',
    'إم تي MT',
  ],
  'بورش Porsche': [
    'كايين Cayenne',
    'ماكان Macan',
    'باناميرا Panamera',
    'بوكستر Boxster',
    'كايمن Cayman',
    'تاكان Takan',
    'تي سي TC',
    'تي آر TR',
    'تي دي TD',
    'تي إف TF',
  ],
  'ميني Mini': [
    'كوبر Cooper',
    'كوبر إس Cooper S',
    'كوبر سي Clubman',
    'كوبر كانتريمان Countryman',
    'كوبر رودستر Roadster',
    'كوبر كوبيه Coupe',
    'كوبر كابريو Convertible',
    'كوبر إس إي SE',
    'كوبر إس بي SP',
    'كوبر إم بي MP',
  ],
  'سانغ يونغ SsangYong': [
    'تيڤولي Tivoli',
    'ريكس턴 Rexton',
    'كوريستو Korando',
    'موسكاني Musso',
    'أكتيون Actyon',
    'ستافيك Stavic',
    'إي إكس EX',
    'إي إم EM',
    'إي تي ET',
    'إي إف EF',
  ],
  'دايهاتسو Daihatsu': [
    'تيريوس Terios',
    'موف Move',
    'ميرا Mira',
    'أتيف Atif',
    'سيروك Charade',
    'بيوز Boon',
    'إي زد EZ',
    'إي إم EM',
    'إي تي ET',
    'إي إف EF',
  ],
  'إيسوزو Isuzu': [
    'دي ماكس D-Max',
    'مولتيفليكس Multiflex',
    'تروبر Trooper',
    'إي سي EC',
    'إي إم EM',
    'إي تي ET',
    'إي إف EF',
    'إي جي EG',
    'إي كي EK',
    'إي إل EL',
  ],
  'أوبل Opel': [
    'كورسا Corsa',
    'أسترا Astra',
    'إنسيجنيا Insignia',
    'جراند لاند Grandland',
    'ميرا Mira',
    'أدم Adam',
    'زيافرا Zafira',
    'كومبو Combo',
    'روك Rock',
    'أرتيف Artiv',
  ],
  'سيات SEAT': [
    'إبيزا Ibiza',
    'ليون Leon',
    'أرونا Arona',
    'أتيكا Ateca',
    'تاراكو Tarraco',
    'ألفانيا Alhambra',
    'ماربيل Marbella',
    'إيبيزا Cupra',
    'إيبيزا FR',
    'إيبيزا XL',
  ],
  'سكودا Skoda': [
    'أوكتافيا Octavia',
    'سوبرب Superb',
    'كاروك Karoq',
    'كودياك Kodiaq',
    'فابيا Fabia',
    'ريبير Rapide',
    'سيتاني Scala',
    'كاميق Kamiq',
    'إنياك Enyaq',
    'رومات Romat',
  ],
  'ألفا روميو Alfa Romeo': [
    'جيوليتا Giulietta',
    'ستلفيو Stelvio',
    'جي لي Giulia',
    'ميتو Mito',
    'برافو Bravo',
    'سبايدر Spider',
    'بريرا Brezza',
    'كاما Cama',
    'فيرو Ferro',
    'بيرو Perro',
  ],
  'فيراري Ferrari': [
    'إف 8 F8',
    'بوروسانج بيرل Burrosang Pearl',
    'بوروسانج روما Burrosang Roma',
    'بوروسانج SF90 Burrosang SF90',
    'بوروسانج 488 Burrosang 488',
    'بوروسانج 812 Burrosang 812',
    'بوروسانج 296 Burrosang 296',
    'بوروسانج 360 Burrosang 360',
    'بوروسانج 458 Burrosang 458',
    'بوروسانج 599 Burrosang 599',
  ],
  'لامبورغيني Lamborghini': [
    'أوراكان Huracán',
    'أفنتادور Aventador',
    'أوروس Urus',
    'غالاردو Gallardo',
    'ديابلو Diablo',
    'موخرا Murciélago',
    'إيستو Estoque',
    'سيان Sián',
    'فينينو Veneno',
    'ريفينتون Reventón',
  ],
  'بنتلي Bentley': [
    'كونتيننتال Continental',
    'بنتايج Bentayga',
    'فلاينج سبير Flying Spur',
    'موليزل Mulsanne',
    'أرناج Arnage',
    'أزور Azure',
    'بروكارد Brooklands',
    'سي إن CN',
    'سي إم CM',
    'سي تي CT',
  ],
  'رولز رويس Rolls-Royce': [
    'فانتوم Phantom',
    'جوست Ghost',
    'رايث Wraith',
    'دول Dawn',
    '库里南 Cullinan',
    'سيلفر سيرفيس Silver Service',
    'كورنيش Corniche',
    'كامارجو Camargue',
    'بيجاس Pegasus',
    'سي نايت SN',
  ],
  'أستون مارتن Aston Martin': [
    'DB11',
    'Vantage',
    'DBS Superleggera',
    'Rapide',
    'Vanquish',
    'Lagonda',
    'Virage',
    'Cygnet',
    'One-77',
    'Valkyrie',
  ],
  'ماكلارين McLaren': [
    '720S',
    '570S',
    'P1',
    'Speedtail',
    'Elva',
    'Artura',
    'GT',
    '600LT',
    '650S',
    'Senna',
  ],
  'لوتس Lotus': [
    'Evora',
    'Elise',
    'Exige',
    'Emira',
    'Esprit',
    'Europa',
    'Evija',
    'Elite',
    'Eterne',
    'Excel',
  ],
  'مازيراتي Maserati': [
    'Quattroporte',
    'Ghibli',
    'Levante',
    'GranTurismo',
    'GranCabrio',
    'MC20',
    'Spyder',
    'Coupe',
    'Biturbo',
    'Merak',
  ],
  'كاديلاك Cadillac': [
    'CT4',
    'CT5',
    'CT6',
    'XT4',
    'XT5',
    'XT6',
    'Escalade',
    'ATS',
    'CTS',
    'ELR',
  ],
  'لينكولن Lincoln': [
    'Continental',
    'Navigator',
    'Nautilus',
    'Corsair',
    'Aviator',
    'MKZ',
    'MKS',
    'MKT',
    'MKX',
    'Mark LT',
  ],
  'كرايسلر Chrysler': [
    '300C',
    'Pacifica',
    'Voyager',
    'PT Cruiser',
    'Crossfire',
    'Sebring',
    'Town & Country',
    'Concorde',
    'Vision',
    'LHS',
  ],
  'رام RAM': [
    '1500',
    '2500',
    '3500',
    'ProMaster',
    'ProMaster City',
    'Dakota',
    'Charger',
    'Challenger',
    'Durango',
    'Nitro',
  ],
  'جي إم سي GMC': [
    'Sierra',
    'Yukon',
    'Terrain',
    'Acadia',
    'Canyon',
    'Savana',
    'Envoy',
    'Jimmy',
    'Sonoma',
    'Typhoon',
  ],
  'بونتياك Pontiac': [
    'Firebird',
    'Trans Am',
    'GTO',
    'Grand Prix',
    'Bonneville',
    'Sunbird',
    'Tempest',
    'Parisienne',
    'Montana',
    'Torrent',
  ],
  'هولدين Holden': [
    'Commodore',
    'Colorado',
    'Cruze',
    'Astra',
    'Barina',
    'Trax',
    'Captiva',
    'Equinox',
    'Malibu',
    'Spark',
  ],
  'بروتون Proton': [
    'Saga',
    'Persona',
    'Iriz',
    'X70',
    'X50',
    'Preve',
    'Exora',
    'Suprima',
    'Gen2',
    'Waja',
  ],
  'بيرلاي Perodua': [
    'Myvi',
    'Axia',
    'Bezza',
    'Kancil',
    'Kenari',
    'Kelisa',
    'Viva',
    'Alza',
    'Ativa',
    'Aruz',
  ],
  'تاتا Tata': [
    'Nexon',
    'Harrier',
    'Tiago',
    'Tigor',
    'Altroz',
    'Safari',
    'Sumo',
    'Indica',
    'Indigo',
    'Manza',
  ],
  'ماهيندرا Mahindra': [
    'Scorpio',
    'XUV500',
    'Thar',
    'Bolero',
    'Marazzo',
    'KUV100',
    'TUV300',
    'Alturas G4',
    'Verito',
    'e2oPlus',
  ],
  'ماروتي سوزوكي Maruti Suzuki': [
    'Swift',
    'Dzire',
    'Baleno',
    'Vitara Brezza',
    'Ertiga',
    'Wagon R',
    'Celerio',
    'Ignis',
    'S-Presso',
    'Alto',
  ],
  'فاو FAW': [
    'Bestune T77',
    'Bestune T99',
    'Bestune B70',
    'Bestune B30',
    'Bestune X40',
    'Bestune X80',
    'Bestune N7',
    'Bestune N5',
    'Bestune N3',
    'Bestune N1',
  ],
  'جاك JAC': [
    'S2',
    'S3',
    'S4',
    'S7',
    'iEV6E',
    'iEV7S',
    'Refine M1',
    'Refine M3',
    'Refine M5',
    'Refine M6',
  ],
  'جريت وول Great Wall': [
    'Haval H6',
    'Haval H9',
    'Haval F7',
    'Poer',
    'Wingle 7',
    'Ora R1',
    'Ora Good Cat',
    'Tank 300',
    'Tank 500',
    'Tank 700',
  ],
  'بريليانس Brilliance': [
    'H530',
    'V5',
    'V6',
    'V7',
    'M2',
    'M3',
    'M8',
    'FRV',
    'F50',
    'BS4',
  ],
  'تشانجان Changan': [
    'CS35 Plus',
    'CS55 Plus',
    'CS75 Plus',
    'Uni-T',
    'Uni-K',
    'Alsvin',
    'Raeton CC',
    'Eado',
    'Eado Plus',
    'Benni',
  ],
  'جيلي Geely': [
    'Emgrand',
    'Coolray',
    'Azkarra',
    'Monjaro',
    'Preface',
    'Atlas',
    'Vision',
    'Icon',
    'Boyue',
    'Binrui',
  ],
  'بورغوارد Borgward': [
    'BX5',
    'BX7',
    'BX6',
    'BX3',
    'BXi7',
    'BXi5',
    'BXi3',
    'BXi2',
    'BXi1',
    'BXi0',
  ],
  'دونغفنغ Dongfeng': [
    'Aeolus AX7',
    'Aeolus E70',
    'Aeolus L7',
    'Fengshen E30',
    'Fengdu MX6',
    'Fengxing SX6',
    'Rich 6',
    'Fengguang 580',
    'Fengguang S560',
    'Fengguang ix5',
  ],
  'زوتي Zotye': [
    'T600',
    'T700',
    'T800',
    'SR7',
    'SR9',
    'Z300',
    'Z500',
    'Z700',
    'Z800',
    'Z1000',
  ],
  'ليفان Lifan': [
    'X50',
    'X60',
    'X70',
    'X80',
    'Solano',
    'Murman',
    'Foison',
    'Smily',
    'Cebrium',
    'Housejoy',
  ],
  'هافال Haval': [
    'H6',
    'H9',
    'H2',
    'H4',
    'H5',
    'F7',
    'F7x',
    'M6',
    'Jolion',
    'Big Dog',
  ],
  'فوتون Foton': [
    'Tunland',
    'Sauvana',
    'Gratour',
    'Pickup',
    'View',
    'Villager',
    'Minibus',
    'Truck',
    'Bus',
    'Van',
  ],
  'سينوفا Sinova': [
    'X25',
    'X35',
    'X55',
    'X75',
    'D50',
    'D60',
    'D70',
    'D80',
    'D90',
    'D100',
  ],
  'روز رايز Roewe': [
    'RX5',
    'RX8',
    'i5',
    'i6',
    'eRX5',
    'ei5',
    'ei6',
    'MARVEL X',
    'MARVEL R',
    'IMAX8',
  ],
  'إم جي MG': [
    'ZS',
    'HS',
    'RX5',
    'RX8',
    'MG5',
    'MG6',
    'MG7',
    'MG8',
    'MG9',
    'MG10',
  ],
  'لادا Lada': [
    'Vesta',
    'Granta',
    'Niva',
    'XRAY',
    'Kalina',
    'Priora',
    'Largus',
    '2101',
    '2102',
    '2103',
  ],
  'غاز GAZ': [
    'Volga',
    'Sobol',
    'Next',
    'Valdai',
    'Sadko',
    'Bear',
    'Business',
    'Cheetah',
    'Crane',
    'Dolphin',
  ],
  'فاز VAZ': [
    '2101',
    '2102',
    '2103',
    '2104',
    '2105',
    '2106',
    '2107',
    '2108',
    '2109',
    '2110',
  ],
  'سايبا Saipa': [
    'Pride',
    'Tiba',
    'Saina',
    'Quick',
    'Shahin',
    '111',
    '131',
    '132',
    '151',
    '171',
  ],
  'إيران خودرو Iran Khodro': [
    'Samand',
    'Dena',
    'Runna',
    'Arisun',
    'Paykan',
    'Peugeot Pars',
    'Peugeot 206',
    'Peugeot 207',
    'Peugeot 405',
    'Peugeot 508',
  ],
  'أبولو Apollo': [
    'Intensa Emozione',
    'Arrow',
    'Evo',
    'N',
    'S',
    'T',
    'U',
    'V',
    'W',
    'X',
  ],
  'أرتيجا Artega': [
    'Scalo',
    'K1',
    'K2',
    'K3',
    'K4',
    'K5',
    'K6',
    'K7',
    'K8',
    'K9',
  ],
  'أرييل Ariel': [
    'Atom',
    'Nomad',
    'Ace',
    'Hipercar',
    'Type 1',
    'Type 2',
    'Type 3',
    'Type 4',
    'Type 5',
    'Type 6',
  ],
  'أوروس Aurus': [
    'Senat',
    'Arsenal',
    'Komendant',
    'Senator',
    'Marshal',
    'General',
    'Colonel',
    'Major',
    'Captain',
    'Lieutenant',
  ],
  'أوسكار Osca': [
    'MT4',
    'FS372',
    '1600 GT',
    '1500 S',
    '2000 GT',
    '2500 GT',
    '3000 GT',
    '3500 GT',
    '4000 GT',
    '4500 GT',
  ],
  'أوليسيس Ulysse': [
    'Type 1',
    'Type 2',
    'Type 3',
    'Type 4',
    'Type 5',
    'Type 6',
    'Type 7',
    'Type 8',
    'Type 9',
    'Type 10',
  ],
  'إدون Edon': [
    'Model 1',
    'Model 2',
    'Model 3',
    'Model 4',
    'Model 5',
    'Model 6',
    'Model 7',
    'Model 8',
    'Model 9',
    'Model 10',
  ],
  'إسكاليد Escalade': [],
  'إف سي في FCV': [],
  'إكستريم Extreme': [],
  'إلكتروميكانيكا Electromeccanica': [],
  'إم في أي MVI': [],
  'إميريتي Emirati': [],
  'إنفينيتي Infiniti': [],
  'إي دي إس EDS': [],
  'إي تي في ETV': [],
  'إيجل Eagle': [],
  'إيكو Eco': [],
  'إيماك Emak': [],
  'إيفوك Evoke': [],
  'إيكاروس Ikarus': [],
  'إيلو Elio': [],
  'أباريث Abarth': [],
  'أراش Arash': [],
  'أرتينجا Artega': [],
  'أرينو Arrinera': [],
  'أستون مارتن Aston Martin': [],
  'ألفا روميو Alfa Romeo': [],
  'أميركان لايفان American LaFrance': [],
  'أميريكان موتورز American Motors': [],
  'أوتوموبيلي تورينو Automobili Torino': [],
  'أوتوموبيلي لامبورغيني Automobili Lamborghini': [],
  'أوتوموبيلي ماتيراتسي Automobili Matarazzi': [],
  'أوتوموبيلي نوتشيولا Automobili Nucciola': [],
  'غير ذلك': [],
};
