'use client';

import { FaCar } from 'react-icons/fa';

export const carBrands = [
  // {
  //   value: 'الماركة',
  //   label: `الماركة ${(<FaCar className="text-one text-lg sm:text-xl" />)}`,
  // },
  { value: 'تويوتا', label: 'تويوتا Toyota' },
  { value: 'فورد', label: 'فورد Ford' },
  { value: 'شيفروليه', label: 'شيفروليه Chevrolet' },
  { value: 'هوندا', label: 'هوندا Honda' },
  { value: 'نيسان', label: 'نيسان Nissan' },
  { value: 'هيونداي', label: 'هيونداي Hyundai' },
  { value: 'كيا', label: 'كيا Kia' },
  { value: 'فولكسفاغن', label: 'فولكسفاغن Volkswagen' },
  { value: 'مرسيدس-بنز', label: 'مرسيدس-بنز Mercedes-Benz' },
  { value: 'بي إم دبليو', label: 'بي إم دبليو BMW' },
  { value: 'أودي', label: 'أودي Audi' },
  { value: 'رينو', label: 'رينو Renault' },
  { value: 'بيجو', label: 'بيجو Peugeot' },
  { value: 'سوزوكي', label: 'سوزوكي Suzuki' },
  { value: 'مازدا', label: 'مازدا Mazda' },
  { value: 'ميتسوبيشي', label: 'ميتسوبيشي Mitsubishi' },
  { value: 'لكزس', label: 'لكزس Lexus' },
  { value: 'جيب', label: 'جيب Jeep' },
  { value: 'دودج', label: 'دودج Dodge' },
  { value: 'فيات', label: 'فيات Fiat' },
  { value: 'فولفو', label: 'فولفو Volvo' },
  { value: 'سوبارو', label: 'سوبارو Subaru' },
  { value: 'جاغوار', label: 'جاغوار Jaguar' },
  { value: 'لاند روفر', label: 'لاند روفر Land Rover' },
  { value: 'تيسلا', label: 'تيسلا Tesla' },
  { value: 'بورش', label: 'بورش Porsche' },
  { value: 'ميني', label: 'ميني Mini' },
  { value: 'سانغ يونغ', label: 'سانغ يونغ SsangYong' },
  { value: 'دايهاتسو', label: 'دايهاتسو Daihatsu' },
  { value: 'إيسوزو', label: 'إيسوزو Isuzu' },
  { value: 'أوبل', label: 'أوبل Opel' },
  { value: 'سيات', label: 'سيات SEAT' },
  { value: 'سكودا', label: 'سكودا Skoda' },
  { value: 'ألفا روميو', label: 'ألفا روميو Alfa Romeo' },
  { value: 'فيراري', label: 'فيراري Ferrari' },
  { value: 'لامبورغيني', label: 'لامبورغيني Lamborghini' },
  { value: 'بنتلي', label: 'بنتلي Bentley' },
  { value: 'رولز رويس', label: 'رولز رويس Rolls-Royce' },
  { value: 'أستون مارتن', label: 'أستون مارتن Aston Martin' },
  { value: 'ماكلارين', label: 'ماكلارين McLaren' },
  { value: 'لوتس', label: 'لوتس Lotus' },
  { value: 'مازيراتي', label: 'مازيراتي Maserati' },
  { value: 'كاديلاك', label: 'كاديلاك Cadillac' },
  { value: 'لينكولن', label: 'لينكولن Lincoln' },
  { value: 'كرايسلر', label: 'كرايسلر Chrysler' },
  { value: 'رام', label: 'رام RAM' },
  { value: 'جي إم سي', label: 'جي إم سي GMC' },
  { value: 'بونتياك', label: 'بونتياك Pontiac' },
  { value: 'هولدين', label: 'هولدين Holden' },
  { value: 'بروتون', label: 'بروتون Proton' },
  { value: 'بيرلاي', label: 'بيرلاي Perodua' },
  { value: 'تاتا', label: 'تاتا Tata' },
  { value: 'ماهيندرا', label: 'ماهيندرا Mahindra' },
  { value: 'ماروتي سوزوكي', label: 'ماروتي سوزوكي Maruti Suzuki' },
  { value: 'فاو', label: 'فاو FAW' },
  { value: 'جاك', label: 'جاك JAC' },
  { value: 'جريت وول', label: 'جريت وول Great Wall' },
  { value: 'بريليانس', label: 'بريليانس Brilliance' },
  { value: 'تشانجان', label: 'تشانجان Changan' },
  { value: 'جيلي', label: 'جيلي Geely' },
  { value: 'بورغوارد', label: 'بورغوارد Borgward' },
  { value: 'دونغفنغ', label: 'دونغفنغ Dongfeng' },
  { value: 'زوتي', label: 'زوتي Zotye' },
  { value: 'ليفان', label: 'ليفان Lifan' },
  { value: 'هافال', label: 'هافال Haval' },
  { value: 'فوتون', label: 'فوتون Foton' },
  { value: 'سينوفا', label: 'سينوفا Sinova' },
  { value: 'روز رايز', label: 'روز رايز Roewe' },
  { value: 'إم جي', label: 'إم جي MG' },
  { value: 'لادا', label: 'لادا Lada' },
  { value: 'غاز', label: 'غاز GAZ' },
  { value: 'فاز', label: 'فاز VAZ' },
  { value: 'سايبا', label: 'سايبا Saipa' },
  { value: 'إيران خودرو', label: 'إيران خودرو Iran Khodro' },
  { value: 'بروتون', label: 'بروتون Proton' },
  { value: 'بيرلاي', label: 'بيرلاي Perodua' },
  { value: 'تاتا', label: 'تاتا Tata' },
  { value: 'ماهيندرا', label: 'ماهيندرا Mahindra' },
  { value: 'ماروتي سوزوكي', label: 'ماروتي سوزوكي Maruti Suzuki' },
  { value: 'فاو', label: 'فاو FAW' },
  { value: 'جاك', label: 'جاك JAC' },
  { value: 'جريت وول', label: 'جريت وول Great Wall' },
  { value: 'بريليانس', label: 'بريليانس Brilliance' },
  { value: 'تشانجان', label: 'تشانجان Changan' },
  { value: 'جيلي', label: 'جيلي Geely' },
  { value: 'بورغوارد', label: 'بورغوارد Borgward' },
  { value: 'دونغفنغ', label: 'دونغفنغ Dongfeng' },
  { value: 'زوتي', label: 'زوتي Zotye' },
  { value: 'ليفان', label: 'ليفان Lifan' },
  { value: 'هافال', label: 'هافال Haval' },
  { value: 'فوتون', label: 'فوتون Foton' },
  { value: 'سينوفا', label: 'سينوفا Sinova' },
  { value: 'روز رايز', label: 'روز رايز Roewe' },
  { value: 'إم جي', label: 'إم جي MG' },
  { value: 'لادا', label: 'لادا Lada' },
  { value: 'غاز', label: 'غاز GAZ' },
  { value: 'فاز', label: 'فاز VAZ' },
  { value: 'سايبا', label: 'سايبا Saipa' },
  { value: 'إيران خودرو', label: 'إيران خودرو Iran Khodro' },
  { value: 'أبولو', label: 'أبولو Apollo' },
  { value: 'أرتيجا', label: 'أرتيجا Artega' },
  { value: 'أرييل', label: 'أرييل Ariel' },
  { value: 'أستون مارتن', label: 'أستون مارتن Aston Martin' },
  { value: 'ألفا روميو', label: 'ألفا روميو Alfa Romeo' },
  { value: 'أوبل', label: 'أوبل Opel' },
  { value: 'أودي', label: 'أودي Audi' },
  { value: 'أوروس', label: 'أوروس Aurus' },
  { value: 'أوسكار', label: 'أوسكار Osca' },
  { value: 'أوليسيس', label: 'أوليسيس Ulysse' },
  { value: 'إدون', label: 'إدون Edon' },
  { value: 'إسكاليد', label: 'إسكاليد Escalade' },
  { value: 'إف سي في', label: 'إف سي في FCV' },
  { value: 'إكستريم', label: 'إكستريم Extreme' },
  { value: 'إلكتروميكانيكا', label: 'إلكتروميكانيكا Electromeccanica' },
  { value: 'إم جي', label: 'إم جي MG' },
  { value: 'إم في أي', label: 'إم في أي MVI' },
  { value: 'إميريتي', label: 'إميريتي Emirati' },
  { value: 'إنفينيتي', label: 'إنفينيتي Infiniti' },
  { value: 'إي دي إس', label: 'إي دي إس EDS' },
  { value: 'إي تي في', label: 'إي تي في ETV' },
  { value: 'إيجل', label: 'إيجل Eagle' },
  { value: 'إيكو', label: 'إيكو Eco' },
  { value: 'إيماك', label: 'إيماك Emak' },
  { value: 'إيفوك', label: 'إيفوك Evoke' },
  { value: 'إيكاروس', label: 'إيكاروس Ikarus' },
  { value: 'إيلو', label: 'إيلو Elio' },
  { value: 'إيماك', label: 'إيماك Emak' },
  { value: 'أباريث', label: 'أباريث Abarth' },
  { value: 'أراش', label: 'أراش Arash' },
  { value: 'أرتينجا', label: 'أرتينجا Artega' },
  { value: 'أرينو', label: 'أرينو Arrinera' },
  { value: 'أستون مارتن', label: 'أستون مارتن Aston Martin' },
  { value: 'ألفا روميو', label: 'ألفا روميو Alfa Romeo' },
  { value: 'أميركان لايفان', label: 'أميركان لايفان American LaFrance' },
  { value: 'أميريكان موتورز', label: 'أميريكان موتورز American Motors' },
  { value: 'أوبل', label: 'أوبل Opel' },
  {
    value: 'أوتوموبيلي تورينو',
    label: 'أوتوموبيلي تورينو Automobili Torino',
  },
  {
    value: 'أوتوموبيلي لامبورغيني',
    label: 'أوتوموبيلي لامبورغيني Automobili Lamborghini',
  },
  {
    value: 'أوتوموبيلي ماتيراتسي',
    label: 'أوتوموبيلي ماتيراتسي Automobili Matarazzi',
  },
  {
    value: 'أوتوموبيلي نوتشيولا',
    label: 'أوتوموبيلي نوتشيولا Automobili Nucciola',
  },
  { value: 'غير ذلك', label: 'غير ذلك' },
];
