import {
  FaSmile,
  FaSprayCan,
  FaTint,
  FaSun,
  FaPalette,
  FaLipstick,
  FaEye,
  FaHaircut,
  FaSoap,
  FaTooth,
  FaBrush,
  FaBath,
  FaHandSparkles,
  FaLotionBottle,
} from 'react-icons/fa';
import { GiRazor, GiPerfumeBottle } from 'react-icons/gi';
import { MdFaceRetouchingNatural, MdOutlineShower } from 'react-icons/md';

const beauty = [
  {
    name: 'productType',
    label: 'نوع المنتج',
    icon: <FaSmile className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'مكياج',
      2: 'العناية بالبشرة',
      3: 'العناية بالشعر',
      4: 'عطور',
      5: 'أدوات تجميل',
      6: 'حلاقة',
      7: 'العناية بالفم',
      8: 'الاستحمام والجسم',
      9: 'العناية بالأظافر',
      10: 'أخرى',
    },
  },
  {
    name: 'makeupType',
    label: 'نوع المكياج',
    icon: <FaLipstick className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'وجه (أساس، كونسيلر، بودرة)',
      2: 'عيون (ظلال، كحل، ماسكارا)',
      3: 'شفاه (أحمر شفاه، ملمع شفاه)',
      4: 'خدود (بلاشر، برونزر)',
      5: 'مثبت مكياج',
      6: 'أخرى',
    },
  },
  {
    name: 'skinCareType',
    label: 'نوع العناية بالبشرة',
    icon: (
      <MdFaceRetouchingNatural className="text-primary-500 text-lg sm:text-xl" />
    ),
    placeholder: '-اختر-',
    options: {
      1: 'مرطب',
      2: 'منظف',
      3: 'مقشر',
      4: 'مصل',
      5: 'واقي شمس',
      6: 'كريم عيون',
      7: 'علاج حب الشباب',
      8: 'أخرى',
    },
  },
  {
    name: 'skinType',
    label: 'نوع البشرة',
    icon: <FaSmile className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'عادية',
      2: 'جافة',
      3: 'دهنية',
      4: 'مختلطة',
      5: 'حساسة',
      6: 'معرضة لحب الشباب',
      7: 'ناضجة',
      8: 'أخرى',
    },
  },
  {
    name: 'hairType',
    label: 'نوع الشعر',
    icon: <FaHaircut className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'عادي',
      2: 'جاف',
      3: 'دهني',
      4: 'تالف',
      5: 'معالج بالصبغة',
      6: 'ناعم',
      7: 'سميك',
      8: 'مجعد',
      9: 'مستقيم',
      10: 'أخرى',
    },
  },
  {
    name: 'hairCareType',
    label: 'نوع العناية بالشعر',
    icon: <FaHaircut className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'شامبو',
      2: 'بلسم',
      3: 'ماسك',
      4: 'زيت',
      5: 'مصل',
      6: 'علاج تساقط',
      7: 'صبغة شعر',
      8: 'أخرى',
    },
  },
  {
    name: 'fragranceType',
    label: 'نوع العطر',
    icon: <GiPerfumeBottle className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'بارفان',
      2: 'أودي تواليت',
      3: 'أودي بيرفوم',
      4: 'كولونيا',
      5: 'عطر زيتي',
      6: 'أخرى',
    },
  },
  {
    name: 'color',
    label: 'اللون',
    icon: <FaPalette className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'أسود',
      2: 'بني',
      3: 'أشقر',
      4: 'أحمر',
      5: 'وردي',
      6: 'لون بشري',
      7: 'بنفسجي',
      8: 'أخرى',
    },
  },
  {
    name: 'condition',
    label: 'الحالة',
    icon: <FaSmile className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'جديد',
      2: 'مستعمل',
      3: 'مفتوح وغير مستخدم',
      4: 'أخرى',
    },
  },
];

export default beauty;
