import {
  MdWork,
  MdLocationOn,
  MdAttachMoney,
  MdSchool,
  MdAccessTime,
  MdBusiness,
  MdDescription,
  MdDateRange,
} from 'react-icons/md';
import {
  FaBuilding,
  FaUserTie,
  FaLaptopCode,
  FaBriefcaseMedical,
  FaChartLine,
  FaGraduationCap,
  FaLanguage,
  FaTools,
} from 'react-icons/fa';

const jobs = [
  {
    name: 'title',
    label: 'المسمى الوظيفي',
    icon: <FaUserTie className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: 'مثال: مهندس برمجيات، محاسب، مدير مبيعات',
  },
  {
    name: 'company',
    label: 'الشركة',
    icon: <FaBuilding className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: 'اسم الشركة أو المؤسسة',
  },
  {
    name: 'location',
    label: 'المحافظة',
    icon: <MdLocationOn className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'دمشق',
      2: 'حلب',
      3: 'حمص',
      4: 'اللاذقية',
      5: 'حماة',
      6: 'طرطوس',
      7: 'درعا',
      8: 'السويداء',
      9: 'القنيطرة',
      10: 'دير الزور',
      11: 'الحسكة',
      12: 'الرقة',
      13: 'إدلب',
      14: 'أخرى',
    },
  },
  {
    name: 'salary',
    label: 'الراتب',
    icon: <MdAttachMoney className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: 'يرجى تحديد الراتب بالليرة السورية',
  },
  {
    name: 'employmentType',
    label: 'نوع الوظيفة',
    icon: <MdAccessTime className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'دوام كامل',
      2: 'دوام جزئي',
      3: 'عقد مؤقت',
      4: 'عمل حر',
      5: 'تدريب',
      6: 'عن بعد',
      7: 'أخرى',
    },
  },
  {
    name: 'jobCategory',
    label: 'مجال الوظيفة',
    icon: <MdWork className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'تكنولوجيا المعلومات',
      2: 'المالية والمحاسبة',
      3: 'المبيعات والتسويق',
      4: 'الموارد البشرية',
      5: 'الهندسة',
      6: 'الرعاية الصحية',
      7: 'التعليم',
      8: 'البناء والمقاولات',
      9: 'الخدمات',
      10: 'أخرى',
    },
  },
  {
    name: 'educationLevel',
    label: 'المؤهل العلمي',
    icon: <FaGraduationCap className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'ثانوية عامة',
      2: 'دبلوم',
      3: 'بكالوريوس',
      4: 'ماجستير',
      5: 'دكتوراه',
      6: 'لا يشترط مؤهل',
    },
  },
  {
    name: 'experience',
    label: 'الخبرة المطلوبة',
    icon: <FaChartLine className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'لا تشترط خبرة',
      2: 'أقل من سنة',
      3: '1-3 سنوات',
      4: '3-5 سنوات',
      5: '5-10 سنوات',
      6: 'أكثر من 10 سنوات',
    },
  },
  {
    name: 'skills',
    label: 'المهارات المطلوبة',
    icon: <FaLaptopCode className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: 'مثال: لغة انكليزية، برمجة، إدارة مشاريع...',
  },
  {
    name: 'description',
    label: 'وصف الوظيفة',
    icon: <MdDescription className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: 'أدخل وصفاً مفصلاً للوظيفة والمهام المطلوبة',
  },
  {
    name: 'deadline',
    label: 'آخر موعد للتقديم',
    icon: <MdDateRange className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: 'حدد تاريخ انتهاء التقديم',
  },
];

export default jobs;
