import {
  FaCouch,
  FaChair,
  FaTable,
  FaBed,
  FaPalette,
  FaUtensils,
  FaBlender,
  FaFire,
  FaThermometerHalf,
  FaLightbulb,
  FaExpand,
  FaRulerCombined,
  FaHome,
} from 'react-icons/fa';
import { FaKitchenSet } from 'react-icons/fa6';
import { GiSofa, GiWardrobe, GiDesk } from 'react-icons/gi';
import { LuTable2 } from 'react-icons/lu';
import { MdMicrowave, MdCoffeeMaker, MdDishwasher } from 'react-icons/md';

const kitchen = [
  {
    name: 'productType',
    label: 'نوع المنتج',
    icon: <FaHome className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'أثاث',
      2: 'جهاز مطبخ',
      3: 'أدوات مطبخ',
      4: 'ديكور',
      5: 'مفروشات السرير',
      6: 'إضاءة',
      7: 'تخزين',
      8: 'أخرى',
    },
  },
  {
    name: 'furnitureType',
    label: 'نوع الأثاث',
    icon: <GiSofa className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'كنبة',
      2: 'كرسي',
      3: 'طاولة',
      4: 'سرير',
      5: 'خزانة',
      6: 'مكتب',
      7: 'رف',
      8: 'أخرى',
    },
  },
  {
    name: 'tableShape',
    label: 'شكل الطاولة',
    icon: <LuTable2 className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'دائري',
      2: 'مربع',
      3: 'مستطيل',
      4: 'بيضاوي',
      5: 'أخرى',
    },
  },
  {
    name: 'applianceType',
    label: 'نوع الجهاز',
    icon: <FaBlender className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'ثلاجة',
      2: 'فرن',
      3: 'ميكروويف',
      4: 'غسالة صحون',
      5: 'خلاط',
      6: 'آلة صنع القهوة',
      7: 'خلاط كهربائي',
      8: 'محمصة خبز',
      9: 'عصارة',
      10: 'أخرى',
    },
  },
  {
    name: 'cooktopType',
    label: 'نوع الموقد',
    icon: <FaFire className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'غاز',
      2: 'كهرباء',
      3: 'حث',
      4: 'أخرى',
    },
  },
  {
    name: 'capacity',
    label: 'السعة',
    icon: <FaKitchenSet className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: 'باللتر أو القدم المكعب',
    options: {
      1: 'صغير (أقل من 50 لتر)',
      2: 'متوسط (50-100 لتر)',
      3: 'كبير (أكثر من 100 لتر)',
      4: 'أخرى',
    },
  },
  {
    name: 'material',
    label: 'المادة',
    icon: <FaCouch className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'خشب',
      2: 'معدن',
      3: 'زجاج',
      4: 'بلاستيك',
      5: 'سيراميك',
      6: 'ستانلس ستيل',
      7: 'رخام',
      8: 'أخرى',
    },
  },
  {
    name: 'color',
    label: 'اللون',
    icon: <FaPalette className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'أسود',
      2: 'أبيض',
      3: 'بني',
      4: 'رمادي',
      5: 'أحمر',
      6: 'أزرق',
      7: 'أخضر',
      8: 'بيج',
      9: 'ذهبي',
      10: 'فضي',
      11: 'أخرى',
    },
  },
  {
    name: 'style',
    label: 'النمط',
    icon: <FaHome className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'حديث',
      2: 'كلاسيكي',
      3: 'ريفي',
      4: 'بسيط',
      5: 'صناعي',
      6: 'منزل ريفي',
      7: 'اسكندنافي',
      8: 'أخرى',
    },
  },
  {
    name: 'dimensions',
    label: 'الأبعاد',
    icon: <FaRulerCombined className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: 'الطول x العرض x الارتفاع',
  },
  {
    name: 'condition',
    label: 'الحالة',
    icon: <FaHome className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'جديد',
      2: 'مستعمل',
      3: 'مجدد',
      4: 'أخرى',
    },
  },
];

export default kitchen;
