import {
  FaTshirt,
  FaShoes,
  FaHandbag,
  FaPalette,
  FaExpand,
  FaGlasses,
  FaRing,
  FaHatCowboy,
  FaScarf,
  FaWatch,
} from 'react-icons/fa';
import { GiClothes, GiTie, GiUnderwearShorts } from 'react-icons/gi';

const fashion = [
  {
    name: 'type',
    label: 'نوع المنتج',
    icon: <GiClothes className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'ملابس',
      2: 'أحذية',
      3: 'حقائب',
      4: 'إكسسوارات',
      5: 'ملابس داخلية',
      6: 'أحزمة',
      7: 'نظارات',
      8: 'ساعات',
      9: 'أخرى',
    },
  },
  {
    name: 'clothingType',
    label: 'نوع الملابس',
    icon: <FaTshirt className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'تيشرت',
      2: 'قميص',
      3: 'بنطال',
      4: 'جاكيت',
      5: 'بدلة',
      6: 'تنورة',
      7: 'فساتين',
      8: 'ملابس رياضية',
      9: 'أخرى',
    },
  },
  {
    name: 'gender',
    label: 'الجنس',
    icon: <GiTie className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'رجالي',
      2: 'نسائي',
      3: 'أطفال',
      4: 'للجنسين',
      5: 'أخرى',
    },
  },
  {
    name: 'size',
    label: 'المقاس',
    icon: <FaExpand className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'XS',
      2: 'S',
      3: 'M',
      4: 'L',
      5: 'XL',
      6: 'XXL',
      7: 'XXXL',
      8: 'مقاسات أطفال',
      9: 'أخرى',
    },
  },
  {
    name: 'color',
    label: 'اللون',
    icon: <FaPalette className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'أسود',
      2: 'أبيض',
      3: 'أحمر',
      4: 'أزرق',
      5: 'أخضر',
      6: 'أصفر',
      7: 'وردي',
      8: 'رمادي',
      9: 'بني',
      10: 'بيج',
      11: 'أخرى',
    },
  },
  {
    name: 'brand',
    label: 'الماركة',
    icon: <FaTshirt className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'نايكي',
      2: 'أديداس',
      3: 'زارا',
      4: 'H&M',
      5: 'جيس',
      6: 'بولو',
      7: 'لويس فويتون',
      8: 'جوتشي',
      9: 'أخرى',
    },
  },
  {
    name: 'material',
    label: 'المادة المصنوعة منها',
    icon: <FaTshirt className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'قطن',
      2: 'حرير',
      3: 'صوف',
      4: 'دنة',
      5: 'جينز',
      6: 'جلد',
      7: 'بوليستر',
      8: 'أخرى',
    },
  },
  {
    name: 'condition',
    label: 'الحالة',
    icon: <FaTshirt className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'جديد',
      2: 'مستعمل - بحالة ممتازة',
      3: 'مستعمل - بحالة جيدة',
      4: 'مستعمل - بحالة مقبولة',
      5: 'أخرى',
    },
  },
  {
    name: 'season',
    label: 'الموسم',
    icon: <FaTshirt className="text-primary-500 text-lg sm:text-xl" />,
    placeholder: '-اختر-',
    options: {
      1: 'شتوي',
      2: 'صيفي',
      3: 'ربيعي/خريفي',
      4: 'طوال السنة',
      5: 'أخرى',
    },
  },
];

export default fashion;
